### ISSUE TITLE
Support a string argument to "ignore" describing the reason

### ISSUE THREAD

**Issue by ijc** [frondeus/test-case#102]
Since Rust 1.61.0 the argument to an `ignore` attribute has been printed [as part of the test output](https://github.com/rust-lang/rust/pull/92714/). So:
```rust
#[test]
#[ignore = "Some reason"]
fn something() {...}
```
Will result in:
```console
$ cargo test 
...
test something ... ignored, Some reason
```

I believe the syntax has been valid for some releases prior to 1.61.0 (I'm afraid I don't know since when) but was ignored.

It would be great if test_case's `ignore` modifier (and `inconclusive` I suppose) could similarly take an option reason and propagate it so that `cargo test` will show it.

I'm not sure that `#[test_case(INPUT => ignore = "Some reason" OUTPUT)] ` will fit the current syntax but perhaps `#[test_case(INPUT => ignore("Some reason") OUTPUT)]` could work?

**Comment by ijc** [comment]
I assumed we want the reason to be optional, for backward compat so that existing cases do not all need updating and can still use a bare `inconclusive`. Given that then using `()` to surround the reason argument was ambiguous -- since `=> inconclusive ()` should mean a test with output `()` but is treated as one with an empty reason and no output specified. Similar problems exist with `=> inconclusive ("this is the result")` where `this is the result` ended up as the reason not the expected result...

I went with `[]` instead and will open a PR in a moment, `{}` would be an easy change if preferred. Other things (like `<>`) would need more custom handling.

**Comment by frondeus** [comment]
What about `=> inconclusive = "this is reason" ("this is result")`? @luke-biel would that be ambiguous or/and better?

**Comment by luke-biel** [comment]
I think I'm leaning towards `[]` as proposed right now. I don't think that any of these is better, but
`=> ignore = "reason" "result"` may be a bit confusing.
