### ISSUE TITLE
strict float comparisons

### ISSUE THREAD

**Issue by danieleades** [frondeus/test-case#104]
how should one handle float comparisons with this library?

eg.

```rust
#[test_case(0 => 0.0)]
fn get_floatvalue: u128) -> f64 {
    ...
}
```

clippy output-

```
strict comparison of `f32` or `f64`
`#[warn(clippy::float_cmp)]` implied by `#[warn(clippy::pedantic)]`
`f32::EPSILON` and `f64::EPSILON` are available for the `error_margin`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp
```

**Comment by frondeus** [comment]
Well yes, in that case TestCase isn't very smart, it does exactly what you tell it to do - it uses `==` operator to compare floats.

Usually when you are testing floating point arithmetic logic, you should use `<` or `>` with `EPSILON` constant.

In TestCase, however I would recommend using this syntax:
```
#[test_case(1.0 => is almost 2.0 precision f64::EPSILON)]
```
