### ISSUE TITLE
Silencing compared values

### ISSUE THREAD

**Issue by Antiarchitect** [frondeus/test-case#107]
My case is:

```
#[test_case(&"a".repeat(MQTT_TOPIC_MAX_SIZE as usize + 1) => Err(MqttTopicError::ExceedsMaxSize { candidate: String::from("a".repeat(MQTT_TOPIC_MAX_SIZE as usize + 1)) }); "topic MUST NOT encode to more than 65535 bytes")]
```

and the output is filled with long left and right values. Is it possible to silence them optionally?

**Comment by luke-biel** [comment]
We use `assert_eq` underneath, which, in my knowledge, has no mechanism for turning off showing `left` & `right`.
A hacky workaround would be to use complex assertions `with`:
`#[test_case("input" => with |actual: Result<A, B>| assert!(actual == "expected", "assertion comment"); "test case comment")]`
however this is definitelly not optimal.

We didn't consider anything other than automatic `assert_eq` replacement in test-case library scope at this moment, and even that one is only planned, not actively developed.

**Comment by Antiarchitect** [comment]
Thank you @luke-biel for the solutions list. Will try them shortly.
