### ISSUE TITLE
please include LICENSE file in all published crates

### ISSUE THREAD

**Issue by decathorpe** [frondeus/test-case#117]
(*sorry, pressed Enter too quickly*)

According to the terms of the MIT license, all redistributed copies of the source code need to include a copy of the license text:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

The test-case-core and test-case-macros crates published and distributed via crates.io don't contain a copy of the license text right now.

If you publish from Unix-y system, adding symbolic links that point to the license file in the project's root directory is enough for "cargo publish" to pick them up. On windows, full copies of the file are needed, as far as I know.

**Comment by luke-biel** [comment]
Added links now, along 3.1 release

**Comment by decathorpe** [comment]
Thanks! 🚀
