### ISSUE TITLE
Type as test case argument

### ISSUE THREAD

**Issue by SiKreuz** [frondeus/test-case#123]
I have some test cases that shall test the same method, but the different implementations of it. So I have multiple structs this method is implemented for. I was thinking about writing a macro and solve the relevant method call using something like this:

```rust
let result = <$type>::deserialize(&buffer);
```

This is working fine. However, I wondered if it is possible to do something similar with the `test_case` crate.

**Comment by luke-biel** [comment]
If there's a common trait connecting these types, then you should be able to use `impl Trait` as an arg. You can see this done in tests: https://github.com/frondeus/test-case/blob/master/tests/acceptance_cases/cases_support_generics/src/lib.rs
Does it solve your use case?

**Comment by luke-biel** [comment]
In your scenario I'd use either
```
#[test_case(b"input" => matches Err("text of an error"))]
```
though this may sometimes be a bit more nuanced due to usage of `match` syntax underneath, or
```
#[test_case(6, INVALID_BUFFER_SIZE_SMALL_STR)]
fn deserialize_small_buffer<T: Deserialize>(min_buff_size: usize, expected: &str) {
    let buffer = vec![0u8; min_buff_size - 1];

    let result = T::deserialize(&buffer);

    assert_eq!(result.is_err(), true);
    assert_eq!(result.err().unwrap(), expected);
}
```
where I do assertions myself, while passing expected value as an argument.

There are also closure validators https://github.com/frondeus/test-case/wiki/Syntax#closure-validator you can look at. But at that point it's just matter of looks and readability of the test.

**Comment by luke-biel** [comment]
I realized after writing my comment that you can't really provide the `T` type in this case, so neither
```
#[test_case(b"input" => matches Err("text of an error"))]
```
nor
```
#[test_case(6, INVALID_BUFFER_SIZE_SMALL_STR)]
fn deserialize_small_buffer<T: Deserialize>(min_buff_size: usize, expected: &str) {
    let buffer = vec![0u8; min_buff_size - 1];

    let result = T::deserialize(&buffer);

    assert_eq!(result.is_err(), true);
    assert_eq!(result.err().unwrap(), expected);
}
```
would work.

I could expect that there's a way to overcome this issue with
```
#[test_case(b"input" => matches Result::<Model1, _>::Err("text of an error")]
```
but this ain't the prettiest solution.

There are however closure validators https://github.com/frondeus/test-case/wiki/Syntax#closure-validator and function validators https://github.com/frondeus/test-case/wiki/Syntax#function-validator you can look at. In the latter case you may be able to create a tester method that's also generic, eg.:

```
fn check_err<T: Deserialize>(expected: &'static str) -> impl Fn(Result<T, &'static str>) {
    move |actual: Result<T, &'static str>| {
        assert_eq!(expected, actual.unwrap_err())
    }
}

#[test_case(SIZE => using check_err::<Model1>("expected error string")]
```

**Comment by SiKreuz** [comment]
> I could expect that there's a way to overcome this issue with
> ```rust
> #[test_case(b"input" => matches Result::<Model1, _>::Err("text of an error")]
> ```
> but this ain't the prettiest solution.

I also tried out that idea. Works for now and would be a solution I can work with for now.

What I don't like about the two solutions you mentioned, is that I have to hard-code the error message. Would be nicer to use the const instead. So I can change the error message later and that does not break the tests.

**Comment by SiKreuz** [comment]
Can you help me out. How would I do this here?

**Comment by SiKreuz** [comment]
Just for the record. With someting like this I got it to work. 
```rust
#[test_case(b"input" => matches Result::<Model1, _>::Err(x) if x == SOME_ERROR_STRING_CONST)]
```

@luke-biel Thanks for the help!
