### ISSUE TITLE
error[E0432]: unresolved import `test_case_macros::test_matrix` using 3.2.0

### ISSUE THREAD

**Issue by jtmoon79** [frondeus/test-case#130]
### Problem

I've run into build error

```text
$ cargo test
   ...
   Compiling test-case v3.2.0
error[E0432]: unresolved import `test_case_macros::test_matrix`
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/test-case-3.2.0/src/lib.rs:95:9
   |
95 | pub use test_case_macros::test_matrix;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `test_matrix` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `test-case` (lib) due to previous error
```

Once I run into this error, it seems to persist even after changing the `Cargo.toml` version of `test-case`. In other words, I can
1. change `Cargo.toml` dependency
   ```
   [dev-dependencies]
   test-case = "3.2.0"
   ```
2. run `cargo test`, the error shown above occurs
3. change `Cargo.toml` dependency
   ```
   [dev-dependencies]
   test-case = "3.1.0"
   ```
4. run `cargo test`, the error shown above occurs

Getting out of this strangely persistent error required help from `cargo-cache` (`cargo install cargo-cache`)
```text
cargo cache --autoclean
cargo clean
git restore Cargo.lock
```

### Reproduction

Unfortunately, I could not reproduce this strange error in a new project.

Given this simple `src/main.rs`
```rust
fn main() {}

fn print_num(a: i32) {
    println!("a is {}", a);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ::test_case::test_matrix;

    #[test_matrix(0..2)]
    fn print_num_tests(a: i32) {
        print_num(a);
    }
}
```

I copied `Cargo.toml` settings [my project that elicits the error](https://github.com/jtmoon79/super-speedy-syslog-searcher/) into this new project. Yet, the error never occurred in that new project.

Using rust 1.72.0 on Ubuntu 22.

<br/>

I know there's not much you can do with this bug since there is no reproduction steps. I thought I'd report it in case others run into the same problem.

**Comment by luke-biel** [comment]
I kind of see where this error may have originated. Let me check it out.

**Comment by luke-biel** [comment]
Okay, my best bet is that you did a partial update `cargo update -p test-case`. Our crate has two dependencies `test-case-macros` and `test-case-core`, but our main Cargo.toml file locks against `3.0.0`, so updating only `test-case` didn't prompt Cargo to update the subcrates too. I'm gonna release a fix version with stricter version requirements on children, this should fix it for everyone.

**Comment by jtmoon79** [comment]
The 3.2.1 release fix the build problem. Thanks so much!
