### ISSUE TITLE
Add support for empty test case

### ISSUE THREAD

**Issue by frondeus** [frondeus/test-case#33]
```
#[test_case()]
fn should_work() {}
```

```
#[test_case( ; "name")]
fn should_definitely_work() {}
```

### Questions:
How to generate test case name if there are no arguments.

**Comment by luke-biel** [comment]
Do we even want to consider this? It's basically `#[test]` macro usage.
Other languages disambiguate between cases and unique tests, so I don't think we need to push for the use of `test-case` in every testing condition.
@frondeus ?

**Comment by frondeus** [comment]
To be fair I don't remember why I needed it. We can close it for now and reopen in the future

**Comment by luke-biel** [comment]
Then I'm closing it.
