### ISSUE TITLE
Combination with other attributes than test_case

### ISSUE THREAD

**Issue by emakryo** [frondeus/test-case#52]
Are there any way to combine test_case with other attributes which can be applied to test functions e.g. [serial_test](https://crates.io/crates/serial_test)?

I cannot compile the following example at v1.0.0 (and serial_test = "0.5.1"), 
```rust
    #[test_case(1)]
    #[test_case(2)]
    #[serial_test::serial]
    fn need_to_be_serial(x: i32) {
        assert!(x > 0);
    }
```

**Comment by luke-biel** [comment]
🤔  It should work just like that...
I'll try to check this in spare time.

**Comment by luke-biel** [comment]
It seems that my `async` PR #48 fixes this as well. It's merged into master, but not yet released. As I'm not sure when are we gonna release new version (need to discuss this with @frondeus ) you may want to bind to git dependency:
`test-case = { git = "https://github.com/frondeus/test-case.git" }`.

It would be nice if you could confirm that it's indeed fixed.

**Comment by emakryo** [comment]
I confirmed that it worked using the latest master branch.
Thank you!

**Comment by sazzer** [comment]
I've just confirmed myself that this works with `#[actix_rt::test]` as well, in case anyone is looking.
