### ISSUE TITLE
Syn 1.0.58 breaks test-case

### ISSUE THREAD

**Issue by sminez** [frondeus/test-case#60]
https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7

pinning to 1.0.57 should fix, or updating the import from `export` to `__private`.

Example error in github actions:
```
error[E0432]: unresolved import `syn::export`
 --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/test-case-1.0.0/src/test_case.rs:3:10
  |
3 | use syn::export::TokenStream2;
  |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `test-case`
```

I tried raising on syn but it looks like @dtolnay has made raising issues there restricted to contributors. This feels like it shouldn't have been a patch release?

**Comment by strohel** [comment]
Per comments in https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7, it looks like using `syn::export` was discouraged in the first place.

The proper fix is probably
```diff
-use syn::export::TokenStream2;
+use proc_macro2::TokenStream as TokenStream2
```
...as suggested in unrelated https://github.com/nushell/nushell/issues/2867#issuecomment-754995399.

I'll submit a PR. CC @jxs @application-developer-DA.

**Comment by luke-biel** [comment]
Code is in master. I will discuss releasing 1.1 as soon as we can with @frondeus

**Comment by strohel** [comment]
Cool, thanks for such a quick action!

**Comment by sminez** [comment]
Thank you for the speedy turn around! Sorry I didn't have time to raise the fix myself, spotted it in a hobby project just before starting work this morning :smile:
