### ISSUE TITLE
Question: Timeline for a 1.0.1 release?

### ISSUE THREAD

**Issue by jasonish** [frondeus/test-case#62]
I noticed that commits have been made to fix the issue with syn 1.0.58.  Will a 1.0.1 be released soon to address this?
Thanks.

**Comment by saona-raimundo** [comment]
For the moment, the temporary fix I used is to use directly the GitHub version by using this in `Cargo.toml`
```rust
test-case = { git = "https://github.com/frondeus/test-case" }
```

Just in case someone needs a solution right now.

**Comment by luke-biel** [comment]
Other option is to lock `syn` via cargo patch.
We are working on release.

**Comment by jasonish** [comment]
> For the moment, the temporary fix I used is to use directly the GitHub version by using this in `Cargo.toml`
> 
> ```rust
> test-case = { git = "https://github.com/frondeus/test-case" }
> ```
> 
> Just in case someone needs a solution right now.

Yeah, this is what I've done for now.

**Comment by jasonish** [comment]
> Other option is to lock `syn` via cargo patch.

This requires pointing to a new location as well.  Its too bad patch can't be used to just lock the versions, at least I haven't been able to make it work.

**Comment by ndmitchell** [comment]
> We are working on release.

Any idea how long it will take to make that release? I've got a hack in place to keep things working on my end, but depending on the timing, I might need to switch to something a bit more robust. Thanks for your work on fixing the issue and making the release!

**Comment by luke-biel** [comment]
@frondeus

**Comment by frondeus** [comment]
Hi sorry for the long delay, it was a hard year.
I just released Test-Case v1.1.0.

Furthermore, to prevent such a scenario where I am unavailable, I'm going to add @luke-biel as an additional owner of the crate in crates.io.

**Comment by victorjulien** [comment]
Would you consider pushing a patch release for this issue as well (e.g. a `1.0.1`)? The `1.1.0` release seems to have increased the MSRV which means we still have build failures in our stable branch supporting a MSRV of 1.34.2.
![Screenshot from 2021-01-12 07-51-56](https://user-images.githubusercontent.com/32410611/104280806-c1f37c80-54ac-11eb-9998-1714a15e33c5.png)

**Comment by luke-biel** [comment]
I was aware `async` bumps msrv to 1.39 when I implemented it, but goal was to keep everyone using older versions of rust on 1.0. It has slipped in my mind that change with syn forces everyone to bump. I may consider `1.0.1` for that reason.

**Comment by luke-biel** [comment]
https://github.com/frondeus/test-case/releases/tag/v1.0.1 - it's pushed to crates.io

**Comment by victorjulien** [comment]
Thanks a lot @luke-biel!
