### ISSUE TITLE
Regression from 1.2.1 -> 1.2.2: "return-type but no exected clause" failing to compile

### ISSUE THREAD

**Issue by gh0st42** [frondeus/test-case#86]
Tests that were valid in 1.2.1 fail to compile with 1.2.2

an example can be seen [here](https://github.com/dtn7/bp7-rs/blob/34da1262d171431bf374a923746b0dfa56671915/src/eid.rs#L507):
```rust
#[test_case("dtn:none" => "dtn:none" ; "when using none endpoint")]
#[test_case("dtn:n1/" => panics "" ; "when using dtn endpoint without double slash")]
#[test_case("dtn:none" => EndpointID::none().to_string() ; "when providing node eid and constructed none")]
fn from_str_tests(input_str: &str) -> String {
  EndpointID::try_from(input_str).unwrap().to_string()
}
```

The compiler gives the following error:
```
error: Test function from_str_tests has a return-type but no exected clause in the test-case. This is currently unsupported. See test-case documentation for more details.
   --> src/eid.rs:507:43
    |
507 |     fn from_str_tests(input_str: &str) -> String {
    |                                           ^^^^^^
```

Also, there seems to be a typo in the error message as `exected` should probably be `expected`.

Did the syntax change? 
The changelog does not document any breaking changes regarding this.

**Comment by frondeus** [comment]
@luke-biel - It's seems that we missed `panics` scenario.

@gh0st42 - it should not be a breaking change, its more a oversight in that case, therefore a bug. Sorry for that.
Please see #50 for more context.

For now, you skip this check by enabling feature `allow_result`.

**Comment by luke-biel** [comment]
Mea culpa. I overlooked this. Fix is on it's way, just needs a review.

**Comment by luke-biel** [comment]
`1.2.3` was just published

**Comment by bspradling** [comment]
I'm still receiving the same error above on `1.2.3` with the following test: 

```rust 
#[test_case("ISBN:1839485743"; "isbn10")]
#[test_case("ISBN:1839485743123"; "isbn13")]
#[tokio::test]
async fn test_bibliography_key_serde(expected: &str) -> Result<(), Box<dyn Error>> {
    let key: BibliographyKey = serde_json::from_str(expected)?;
    let actual = serde_json::to_string(&key)?;
    assert_eq!(expected, actual);
    Ok(())
}
```

**Comment by frondeus** [comment]
@bspradling In that case this is expected behavior. 

Your tests were passing silently, so even if there was an Err() the test would pass.
For now, v1.2.2 introduced a compile-time error so you can review this test.

Currently `test_case` does not support implicit `Result<(), Box<dyn Error>>` handling which was introduced in Edition 2018.
To solve this problem you should use test case syntax to expect value explicitly.

In your case:

```rust
#[test_case("ISBN:1839485743" => Ok(()) ; "isbn10")]
#[test_case("ISBN:1839485743123" => Ok(()) ; "isbn13")]
#[tokio::test]
async fn test_bibliography_key_serde(expected: &str) -> Result<(), Box<dyn Error>> {
    let key: BibliographyKey = serde_json::from_str(expected)?;
    let actual = serde_json::to_string(&key)?;
    assert_eq!(expected, actual);
    Ok(())
}
```

This should work.

We know that in long term we need to allow implicit `Result<(), dyn Err>` but our priority was to first prevent any silently failing cases. I hope you understand it.

**Comment by bspradling** [comment]
Ah! Good to know about the silent failures! 

I initially tried your suggestion to resolve the issue but you run into:

```rust
30 | #[test_case("ISBN:1839485743" => Ok(()); "isbn10")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `dyn StdError == dyn StdError`
   |
   = help: the trait `PartialEq` is not implemented for `dyn StdError`
   = note: required because of the requirements on the impl of `PartialEq` for `Box<dyn StdError>`

```

**Comment by frondeus** [comment]
Allright, I think this one deserves its own issue. Let me create one and then we should continue figuring out the right approach for it :)

**Comment by frondeus** [comment]
Actually it might be just a edge-case of #50

**Comment by frondeus** [comment]
@gh0st42 - Is your case solved?

**Comment by gh0st42** [comment]
> @gh0st42 - Is your case solved?

yes, version 1.2.3 works again even without the `allow_result` feature.
thank you for the quick response.
