### ISSUE TITLE
Generate test case for each enum variant

### ISSUE THREAD

**Issue by ollien** [frondeus/test-case#94]
`JUnit` has a really nice feature where, given an enum, you can make a test that will generate an instance of the test for each member of the enum. For instance, you could have something like this

```java
public enum Player {
	PLAYER1, PLAYER2;
}

@ParameterizedTest
@EnumSource(Player.class)
void initializingTheGameStartsWithTheGivenPlayer(Player initialPlayer) {
	// ...
}
```

It would be cool if you could do something like this with `test_case`

```rs
enum Player {
	Player1,
	Player2,
}

#[test_case(Player)]
fn test_for_each_player(player: Player) {
	// ...
}
```

Now, obviously this wouldn't work if the enum had values attached to any of the variants, but at least for this specific case, it prevents you from forgetting to add a test case when you add an enum variant (since it would be auto-generated)

**Comment by luke-biel** [comment]
I could see use for this, however there's one problem with this - it requires us to add an extra derive/attribute to enum as rust has no support for reflection / I know no way of extracting enum values at compile time without adding extra code.
I will think about it.
